[package]
name = "hledger-desktop"
description = "Desktop GUI for the hledger accounting tool"
version = "0.0.1"
authors = [ "Nikita Galaiko <nikita@galaiko.rocks>" ]
edition = "2021"
repository = "https://github.com/ngalaiko/hledger-desktop"
license = "MIT"

[dependencies]
rand = "0.8.5"
rfd = "0.11.0"
serde = { version = "1.0", features = [] }
tauri = { version = "=2.0.0-alpha.10", features = [] }
tauri-utils = { version = "=2.0.0-alpha.6" }
tauri-egui = { git = "https://github.com/Shays-Forks/tauri-egui.git", branch = "0.22" }
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
url = "2.2"
tokio = { version = "1.29.1", features = [ "sync", "macros" ] }
reqwest = "0.11.18"
poll-promise = { version = "0.2.0", features = [ "tokio" ] }
chrono = { version = "0.4.26", features = [ "serde" ] }
tokio-util = "0.7.8"
futures = "0.3.28"
egui_extras = { version = "0.22", features = [ "chrono" ] }
tauri-plugin-shell = "2.0.0-alpha.0"
serde_json = "1.0.104"
egui-modal = "0.2.4"
regex = "1.9.1"
lazy_static = "1.4.0"
egui_autocomplete = { git = "https://github.com/ngalaiko/egui_autocomplete", branch = "master" }

[build-dependencies]
tauri-build = { version = "=2.0.0-alpha.6", features = [] }

[features]
custom-protocol = ["tauri/custom-protocol"]

[profile.release]
codegen-units = 1 # Compile crates one after another so the compiler can optimize better
lto = true        # Enables link to optimizations
opt-level = "s"   # Optimize for binary size
strip = true      # Remove debug symbols
