[build]
devPath = "src"
distDir = "src"

[tauri.bundle]
active = true
externalBin = [ "binaries/hledger-web" ]
targets = [ "app", "dmg" ]
icon = [ "icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png", "icons/icon.icns", "icons/icon.ico" ]
identifier = "rocks.galaiko.hledger.desktop"
category = "Finance"
copyright = "Copyright (c) 2023 Nikita Galaiko"

[plugins.shell]
scope = [ { name = "binaries/hledger-web", sidecar = true, args = true } ]
