[package]
name = "hledger-desktop"
description = "Desktop GUI for the hledger accounting tool"
version = "1.0.0-beta.1"
authors = ["Nikita Galaiko <nikita@galaiko.rocks>"]
edition = "2021"
repository = "https://github.com/ngalaiko/hledger-desktop"
license = "MIT"

[dependencies]
hledger-parser.workspace = true

iced = { version = "0.13", features = [ "debug", "smol" ] }
tracing = "0.1"
tracing-subscriber = "0.3"
smol = "1.0"
rfd = "0.15"
glob = "0.3"
thiserror = "2.0"

[lints]
workspace = true
