name: rust build and test

on:
  push: {}
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Uninstall homebrew
        run: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"

      - name: Install egui dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev libssl-dev

      - name: Install hledger
        uses: ngalaiko/setup-hledger@v1

      - name: clippy
        run: |
          cargo install clippy-sarif sarif-fmt
          cargo clippy \
            --all-features \
            --message-format=json | clippy-sarif | tee rust-clippy-results.sarif | sarif-fmt
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: rust-clippy-results.sarif
          wait-for-processing: true

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose
